config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
   get 'cart', to: 'cart#show'
   post 'cart/add'
   post 'cart/remove'
   get '/about', to: 'pages#aboutus'
   get '/zandbad', to: 'pages#zandbad'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :products, through: :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :product_orders
  has_many :products, through: :product_orders
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_orders
  has_many :orders, through: :product_orders
  has_many :orderables
  has_many :carts, through: :orderables
  has_one_attached :photo
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_render_cart
  before_action :initialize_cart

  def set_render_cart
    @render_cart = true
  end

  def initialize_cart
    @cart ||= Cart.find_by(id: session[:cart_id])

    if @cart.nil?
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show

  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity:)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity:)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart',
                                                   partial: 'cart/cart',
                                                   locals: { cart: @cart }),
                              turbo_stream.replace('cart_items')]
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart',
                                                  partial: 'cart/cart',
                                                  locals: { cart: @cart })
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def aboutus
  end

  def home
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <h1>Cart</h1>
  <% if @cart.orderables.count > 0 %>
    <%= render "cart/orderables" %>
    <p>Total: <%= @cart.total %></p>
    <% else %>
    <p>your cart is empty</p>
    <% end %>
<% end %>

app/views/cart/_orderables.html.erb
<% @cart.orderables.each do |orderable| %>
  <% product = orderable.product %>
  <div id="<%= "cart-#{product.id}" %>">
    <div style="display:flex;justify-content:space-between;margin: 0em 5em;">
      <strong>Name:</strong>
      <%= product.name %>
      <strong>Description:</strong>
      <%= product.description %>
      <strong>Price:</strong>
      <%= product.price %>
      <%= form_with(url: cart_add_path) do |f| %>
        <%= f.hidden_field :id, value: product.id %>
        <%= f.number_field :quantity, value: orderable.quantity, min: 0 %>
        <%= f.submit "Add To Cart" %>
      <% end %>
      <%= form_with(url: cart_remove_path) do |f| %>
        <%= f.hidden_field :id, value: orderable.id %>
        <%= f.submit "X" %>
      <% end %>
      <strong>Total:</strong>
      <%= orderable.total %>
    </div>
  </div>
<% end %>

app/views/cart/show.html.erb
<%= render partial: "cart/cart" if @render_cart %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Majorille Garden</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('logo1.png') %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Baskervville:ital@0;1&family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/19805ed47a.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
<body>
  <a style="text-decoration: none; color: white;" href="/products"><div id="alert" class="alert alert-primary mb-0" style="background-color: #08384B; border: none; color: white; text-align: center; border-radius: 0%" role="alert">
    DE GROOSTE OPENING — <strong>WINKEL NU!</strong>
  </div></a>
  <div class="alert alert-warning alert-dismissible fade show alert-cart" role="alert" style="margin-bottom: 0px;">
  <strong style="margin-right: 5px;">Let op! </strong>    Online bestellingen zijn momenteel niet beschikbaar. De winkelwagen wordt binnenkort geopend!
  <button style="padding-top: 4px;" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
    <%= render "layouts/shared/navbar" %>
  <div class="app-container">
    <%= yield %>
  </div>

  <%= render "layouts/shared/footer" %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<div class="footer">
  <div class="footer-container pt-3">
    <div class="footer-left">
      <%= link_to root_path, class: "footer-brand" do %>
        <%= image_tag('logo1.png') %>
      <% end %>
    </div>
      <div class="left-info">
        <div class="left-link">
          <i id="left-tools" class="fa-solid fa-phone">​</i>
          <p class="info-left">+31636325441</p>
        </div>
        <div class="left-link">
          <i id="left-tools" class="fa-solid fa-envelope"></i>
          <p class="info-left">elbouhlalithami@gmail.com</p>
        ​</div>
        <div class="left-link">
          <i id="left-tools" class="fa-solid fa-map-pin"></i>
          <p class="info-left">Johann siegerstraat 18, Amsterdam</p>
        </div>
      </div>
    <div class="footer-links">
      <a href="https://www.instagram.com/majorillegarden?igsh=MWRibno2ZWE3YTRhYg==" target="_blank"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
  <div class="footer-copyright text-center mb-2">
   © 2024 <a href="" class="href">Majorille Garden</a>
  </div>
  </div>
</div>

app/views/layouts/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="nav-half">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag('logo2.png') %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <div class="nav-half-links">
           <ul class="navbar-nav me-auto">
              <%# if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Over ons", about_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Onze collectie", products_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Zandbad", zandbad_path, class: "nav-link" %>
            </li>
            </ul>
         </div>
       </div>

    <div class="nav-right" >
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li style="padding: 13px;" class="nav-item">
            <%= link_to @cart do %>
            <i id="fonticons" class="fa-solid fa-cart-shopping"></i>
            <%= @cart.products.count %>
            <% end %>
          </li>

        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/aboutus.html.erb
<div class="banner banner-image2">
  <div class="container">
    <h1>Over Majorille Garden</h1>
      <p>Ontdek de magie van de Majorelletuin, waar Marokkaanse tradities en biologische producten voor iedereen toegankelijk zijn!</p>
  </div>
</div>

<div class="text-group">
  <div class="about-img">
    <%= image_tag('majori.jpg')  %>
  </div>
  <div>
    <p class="descript" style="margin-bottom: 0px; margin-top: 65px;">
      Majorrile Garden. Onze producten zijn biologisch en vrij van chemicaliën. Ze worden op traditionele wijze met de hand gemaakt,
       rechtstreeks uit de bron. Ons doel is om iedereen toegang te geven tot echte, biologische producten en een gezonde levensstijl.
    </p>
    <p class="descript" style="margin-top: 25px;">
    Bij Majorelle Garden staan we voor natuurlijke en biologische verzorging. Geïnspireerd door de prachtige Jardin Majorelle in Marokko,
    bieden wij hoogwaardige producten op basis van arganolie, bekend om zijn heilzame effecten op huid, haar en welzijn. Onze producten zijn duurzaam,
     ethisch geproduceerd en ondersteunen lokale gemeenschappen in Marokko.
    Wat ons uniek maakt, is onze focus op educatie en klantgerichtheid. We leren klanten hoe ze onze producten optimaal kunnen gebruiken en organiseren
     workshops om de voordelen van natuurlijke verzorging te delen.
    Ons doel is om een vertrouwd merk te zijn dat staat voor kwaliteit, duurzaamheid en een gezondere levensstijl. Samen bouwen we aan een wereld waarin
     biologische verzorging centraal staat.
    </p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner banner-image" >
  <div class="container" style="display: flex; flex-direction: column; align-items: center">
    <h1>Ontdekken Majorille Garden</h1>
      <p>Ontdek onze verjongende recepten gemaakt van biologische ingrediënten uit het hart van Marokko.</p>
      <a class="btn btn-warning button-3 mt-3" href="/products">SHOP NU</a>
  </div>
</div>
<div class="container text-contain">
  <h2 class="title2">HISTORISCH BEWEZEN PRODUCTEN OM UW LICHAAM TE ONTSPANNEN</h2>
  <p class="para2">Onze producten bevatten uitsluitend arganolie van natuurlijke oorsprong, rijk aan essentiële vetzuren, vitamine E en natuurlijke antioxidanten.</p>
  <p class="para2">Volgens hetzelfde recept dat al eeuwenlang wordt doorgegeven.</p>
  <p class="para2">Het resultaat? Een verkwikt, stressvrij lichaam en geest.</p>
  <p class="para2">Al onze producten staan ​​bekend om hun therapeutische, nutritionele en cosmetische eigenschappen. Geschikt voor haar, huid en anti-aging doeleinden</p>
  <a class="btn btn-warning button-3 mt-3 mb-5 p-3" href="/products">Bekijk onze collectie</a>
</div>

app/views/pages/zandbad.html.erb
<div class="banner3 banner-image3" >
  <div class="container" style="display: flex; flex-direction: column; align-items: center">
    <h1>Ontspan in ons zandbad</h1>
      <p>Gebruik psammotherapy voor een gevoel van welzijn en ontspanning.</p>
  </div>
</div>

    <p class="descript">
      Psammotherapie, ook bekend als warmzandtherapie, staat bekend om zijn vaardigheid om ontstekingen te verminderen, ontspanning op te wekken en een aantal andere lichamelijke klachten te verlichten.
     Deze eeuwenoude kunst, afkomstig van Berbers uit de Merzouga regio in Marokko, is de ultieme spa-behandeling die aan al je lichamelijke behoeften voldoet.
      Bij Majorille Garden brengen we de zandduinen van Marokko naar u toe. Bel en reserveer een tijd om onze traditionele praktijken te ervaren!
    </p>

<div class="text-group">
  <div>
    <p class="descript" style="margin-top: 70px; margin-bottom: 10px">
      Onze zandtherapie is een unieke behandeling die het lichaam en de geest in balans brengt. De therapie bestaat uit drie stappen en biedt een authentieke ervaring dankzij onze traditionele methodes. Daarnaast kun je tijdens de procedure kiezen uit drie unieke thema’s die de ervaring volledig afstemmen op jouw wensen.


    </p>
    <p class="descript" style="margin-top: 0px; margin-bottom: 10px">

      De Stappen van de Behandeling
    </p>
    <p class="descript" style="margin-top: 0px; margin-bottom: 10px">
      Gezondheidsformulier invullen
      Voor aanvang van de therapie vragen we je een kort gezondheidsformulier in te vullen. Dit stelt ons in staat de behandeling aan te passen aan jouw specifieke behoeften en de optimale voordelen te garanderen.
    </p>
     <p class="descript" style="margin-top: 0px; margin-bottom: 10px">

      15 minuten ontspannen in een zandbad
      Geniet van een rustgevende sessie van 15 minuten in warm zand. Het zand, verwarmd tot een aangename temperatuur, ontspant je spieren, bevordert de bloedcirculatie en stimuleert het ontgiften van je lichaam. Het biedt een diep gevoel van rust en ontspanning.


    </p>
     <p class="descript" style="margin-top: 0px; margin-bottom: 10px">
      5 minuten massage met arganolie
      De behandeling wordt afgesloten met een luxe massage van 5 minuten met onze hoogwaardige Majorille arganolie. Deze olie voedt en hydrateert de huid, stimuleert de bloedsomloop en laat je achter met een zijdezachte huid en een gevoel van welzijn.


    </p>
      <p class="descript" style="margin-top: 0px; margin-bottom: 10px">
      Thema’s naar Keuze
    </p>
     <p class="descript" style="margin-top: 0px; margin-bottom: 10px">

      Woestijn: Aangepaste verlichting met een warme, gouden gloed, een subtiele goudgeur en rustgevende woestijnmuziek.
      Lavendel: Kalmerende lavendelgeur, ontspannende muziek naar keuze en zachte, rustgevende verlichting.
      Cactus: Verfrissende cactusgeur, verlichting op maat en muziek die pijnverlichting ondersteunt.

      Onze zandtherapie is een combinatie van rust, luxe en personalisatie die je volledig laat ontspannen. Kies jouw favoriete thema en geniet van een serene ervaring

    </p>
      <p class="descript" style="margin-top: 0px; margin-bottom: 50px">
      Onze zandtherapie is een combinatie van rust, luxe en personalisatie die je volledig laat ontspannen. Kies jouw favoriete thema en geniet van een serene ervaring

    </p>
  </div>
  <div class="about-img">
    <%= image_tag('zandbad1.jpg')  %>
  </div>
</div>

app/views/products/index.html.erb
<div class="banner2" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.pikbest.com/wp/202408/beauty-products-display-on-3d-natural-brown-podium-background-for-cosmetic_9744791.jpg!sw800);">
  <div class="container">
    <h1><strong>ALLE PRODUCTEN</strong></h1>
      <p>Ontdek de magie van de Majorelletuin, waar Marokkaanse tradities en biologische producten voor iedereen toegankelijk zijn!</p>
  </div>
</div>


<div class="container mt-5 d-flex flex-row flex-wrap justify-content-center align-items-center w-100">
    <ul class="d-flex flex-row justify-content-evenly align-items-start w-100 gap-3 p-0 flex-wrap" >
      <% @products.each do | product |  %>

          <li class="card card-sizing index-round" >
        <div id="<%= dom_id product %>">
            <% picture = cl_image_tag product.photo.key %>
            <%= link_to picture, product_path(product) %>
            <div class="card-body">
              <h5 class="card-title"><%= link_to product.name, product_path(product), class: "title-href" %></h5>
            <p class= "card-text"><strong>$<%= product.price%></strong></p>
            <%= form_with(url: cart_add_path, action: cart_path) do |f| %>
              <%= f.hidden_field :id, value: product.id  %>
              <%= f.number_field :quantity, value: 0, min: 1, style:"width: 15%; margin-bottom: 5px" %>
              <%= f.submit "Add To Cart", :onclick => "return confirm('Added To Cart!')", style: "width: 100%; border-color: black;", class: "btn btn-outline-primary text-center cart-button" %>
            <% end %>
            </div>
                <% end %>
        </div>
          </li>
    </ul>
  </div>

app/views/products/show.html.erb
 <div class="container-show">
   <%= cl_image_tag @product.photo.key, width: 400, crop: :fill %>
   <div class="show-info">
     <h1 class="show-name"><%= @product.name %></h1>
    <p class="show-description"><%= @product.description %></p>
     <p class="show-price"><strong>€<%= @product.price %></strong></p>
    <%= form_with(url: cart_add_path) do |f| %>
              <%= f.hidden_field :id, value: @product.id  %>
              <%= f.number_field :quantity, value: 0, min: 1 %>
              <%= f.submit "Add To Cart", :onclick => "return confirm('Added To Cart!')", class:"btn btn-outline-warning button-4 mt-3" %>
            <% end %>
    <div style="display: flex;">
      <i style="color: rgba(8, 56, 75, 1);" class="fa-solid fa-circle-check mt-1"></i>
      <p class="ms-2 show-description" style="color: black;">In stock</p>
    </div>
   </div>
 </div>